services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - church-db:/app/backend/data
      - ../assets:/app/assets:ro
    environment:
      - ASSETS_PATH=/app/assets
      - DB_DIR=/app/backend/data
    restart: unless-stopped

volumes:
  church-db:
